#!/bin/sh

# Old invoke script: 
# /usr/bin/invoke_app -t pigmenthunter -C "start_jupyter -A -T @tool main.ipynb" -u anaconda-6

# Creates a "local" storage directory for generated data in 
# the user's home directory. 

toolDirectory=$(dirname $(dirname $0))
userDirectory=${HOME}/PIGMENTHUNTER

mkdir -p ${userDirectory}/data
echo "${toolDirectory}" > ${HOME}/.phtooldir.txt

cp ${toolDirectory}/redirect.ipynb ${HOME}/.phredirect.ipynb

/usr/bin/invoke_app "$@" -t pigmenthunter \
                         -C "start_jupyter -A -T @tool ${userDirectory}/.phredirect.ipynb" \
                                                  -u anaconda-6
